apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: training-hub-universal-cpu
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/distributed-workloads/tree/main/images/universal/training"
    opendatahub.io/notebook-image-name: "Training | Jupyter | PyTorch | CPU | Python"
    opendatahub.io/notebook-image-desc: "Training runtime image for CPU-based fine-tuning and distributed training."
    opendatahub.io/notebook-image-order: "3"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2025.1"
      annotations:
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.9.0"},
            {"name": "Kubeflow SDK", "version": "0.2.0"},
            {"name": "Training Hub", "version": "v0.4.0"}
          ]
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "jupyterlab", "version": "4.4.9"},
            {"name": "transformers", "version": "4.57.1"},
            {"name": "accelerate", "version": "1.10.0"},
            {"name": "peft", "version": "0.17.0"},
            {"name": "trl", "version": "0.21.0"},
            {"name": "numpy", "version": "1.26.4"},
            {"name": "pandas", "version": "2.3.3"},
            {"name": "matplotlib-inline", "version": "0.1.7"},
            {"name": "tensorboard", "version": "2.19.0"},
            {"name": "instructlab-training", "version": "0.12.1"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-training-th03-cuda128-torch28-py312-rhel9
      from:
        kind: DockerImage
        name: odh-kubeflow-trainer-universal-workbench-image-cpu-2025-1
      referencePolicy:
        type: Source
